#Unit 3 - Data Wrangling
##Experiment 12 - To perform preprocessing on a dataset and dealing with missing values

###kushal
###25070123174
###ENTC A2

In [ ]:
import pandas as pd
import numpy as np

df1=pd.DataFrame({'C1':[11,21, np.nan], 'C2':[15, np.nan, np.nan],'C3': [100,200,300]})
df1

     C1    C2   C3
0  11.0  15.0  100
1  21.0   NaN  200
2   NaN   NaN  300

In [ ]:
df1.isna() #Boolean Function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:
#columnwise na values
df1.isna().sum()

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
#NaN rows are dropped
df1.dropna()

     C1    C2   C3
0  11.0  15.0  100

In [ ]:
df1.fillna(value='DEFAULT')

        C1       C2   C3
0     11.0     15.0  100
1     21.0  DEFAULT  200
2  DEFAULT  DEFAULT  300

In [ ]:
#Mean values of the columns are calculates
df1.fillna(df1.mean())

     C1    C2   C3
0  11.0  15.0  100
1  21.0  15.0  200
2  16.0  15.0  300

##Preprocessing on Dataset 1

In [ ]:
data = {
    "Roll no" : [1,2,3,4,5,6,7,8],
    "Name" : ["A", "B", "C", "D", "E", "F", "G", "H"],
    "Age" : [20, "-", 21, 19, 20, 22, 21, "20"],
    "Marks" : [99, 87, 76, "-", 88, 95, 91, 89],
    "Department" : ["ECE", "cse", "MECH", "CIVIL", "cse", "ECE", "MECH", "CIVIL"],
    "AdmissionDate" : ["20-06-2025", "21-06-2025", "17-06-2025", "03-06-2026", "01-07-2025", "10/06/2025", "05-06-2025", "28-06-2025"]

}
df = pd.DataFrame(data)

#Save as CSV
df.to_csv("data.csv", index=False)

In [ ]:
#Replace "-" with NaN to mark missing values

df.replace("-",np.nan,inplace=True)
df

/tmp/ipykernel_798/879633803.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-",np.nan,inplace=True)

   Roll no Name  Age  Marks Department AdmissionDate
0        1    A   20   99.0        ECE    20-06-2025
1        2    B  NaN   87.0        cse    21-06-2025
2        3    C   21   76.0       MECH    17-06-2025
3        4    D   19    NaN      CIVIL    03-06-2026
4        5    E   20   88.0        cse    01-07-2025
5        6    F   22   95.0        ECE    10/06/2025
6        7    G   21   91.0       MECH    05-06-2025
7        8    H   20   89.0      CIVIL    28-06-2025

In [ ]:
#Convert columns to numeric where needed

df["Age"]= pd.to_numeric(df["Age"], errors="coerce")
df["Marks"]= pd.to_numeric(df["Marks"], errors="coerce")
df

   Roll no Name   Age  Marks Department AdmissionDate
0        1    A  20.0   99.0        ECE    20-06-2025
1        2    B   NaN   87.0        cse    21-06-2025
2        3    C  21.0   76.0       MECH    17-06-2025
3        4    D  19.0    NaN      CIVIL    03-06-2026
4        5    E  20.0   88.0        cse    01-07-2025
5        6    F  22.0   95.0        ECE    10/06/2025
6        7    G  21.0   91.0       MECH    05-06-2025
7        8    H  20.0   89.0      CIVIL    28-06-2025

In [ ]:
#Check missing values

print("\nMissing values:")
print(df.isnull().sum())

Missing values:
Roll no          0
Name             0
Age              1
Marks            1
Department       0
AdmissionDate    0
dtype: int64

In [ ]:
#Fill missing age with mean

df["Age"].fillna(df["Age"].mean(), inplace=True)
df

/tmp/ipykernel_798/1016583343.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

   Roll no Name        Age  Marks Department AdmissionDate
0        1    A  20.000000   99.0        ECE    20-06-2025
1        2    B  20.428571   87.0        cse    21-06-2025
2        3    C  21.000000   76.0       MECH    17-06-2025
3        4    D  19.000000   89.0      CIVIL    03-06-2026
4        5    E  20.000000   88.0        cse    01-07-2025
5        6    F  22.000000   95.0        ECE    10/06/2025
6        7    G  21.000000   91.0       MECH    05-06-2025
7        8    H  20.000000   89.0      CIVIL    28-06-2025

In [ ]:
#Fill missing marks with median

df["Marks"].fillna(df["Marks"].median(),inplace=True)
df

/tmp/ipykernel_798/928270760.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(),inplace=True)

   Roll no Name        Age  Marks Department AdmissionDate
0        1    A  20.000000   99.0        ECE    2025-06-20
1        2    B  20.428571   87.0        CSE    2025-06-21
2        3    C  21.000000   76.0       MECH    2025-06-17
3        4    D  19.000000   89.0      CIVIL    2026-06-03
4        5    E  20.000000   88.0        CSE    2025-07-01
5        6    F  22.000000   95.0        ECE           NaT
6        7    G  21.000000   91.0       MECH    2025-06-05
7        8    H  20.000000   89.0      CIVIL    2025-06-28

In [ ]:
print("\nMissing values:")
print(df.isnull().sum())

Missing values:
Roll no          0
Name             0
Age              0
Marks            0
Department       0
AdmissionDate    0
dtype: int64

In [ ]:
#Fix incosistent text formatting

df["Department"]= df["Department"].str.upper()
df

   Roll no Name        Age  Marks Department AdmissionDate
0        1    A  20.000000   99.0        ECE    20-06-2025
1        2    B  20.428571   87.0        CSE    21-06-2025
2        3    C  21.000000   76.0       MECH    17-06-2025
3        4    D  19.000000   89.0      CIVIL    03-06-2026
4        5    E  20.000000   88.0        CSE    01-07-2025
5        6    F  22.000000   95.0        ECE    10/06/2025
6        7    G  21.000000   91.0       MECH    05-06-2025
7        8    H  20.000000   89.0      CIVIL    28-06-2025

In [ ]:
#Convert admission date to standard datetime format

df["AdmissionDate"]= pd.to_datetime(df["AdmissionDate"], errors= 'coerce')
df

   Roll no Name        Age  Marks Department AdmissionDate
0        1    A  20.000000   99.0        ECE    2025-06-20
1        2    B  20.428571   87.0        CSE    2025-06-21
2        3    C  21.000000   76.0       MECH    2025-06-17
3        4    D  19.000000   89.0      CIVIL    2026-06-03
4        5    E  20.000000   88.0        CSE    2025-07-01
5        6    F  22.000000   95.0        ECE           NaT
6        7    G  21.000000   91.0       MECH    2025-06-05
7        8    H  20.000000   89.0      CIVIL    2025-06-28

In [ ]:
#Save cleaned datasheet

df.to_csv("cleaned_student_data.csv", index = False)
print("\nCleaned CSV file saved as cleaned_student_data")

Cleaned CSV file saved as cleaned_student_data.csv

##Working  on external dataset with missing values

In [ ]:
df=pd.read_csv("/content/Cars93.csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.isna().sum() #Attributes are displayed

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

###Imputing the missing values

In [ ]:
#Luggage Room

df['Luggage.room'] = df['Luggage.room'].fillna(value= df['Luggage.room'].mean())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [ ]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room       0
dtype: int64

In [ ]:
#Rear seat room

df['Rear.seat.room']= df['Rear.seat.room'].fillna(value= df['Rear.seat.room'].mean())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [ ]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room       0
dtype: int64

In [ ]:
#Airbags (Categorical data - use mode)

df['AirBags']= df['AirBags'].fillna(value= df['AirBags'].mode().values[0])
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [ ]:
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [ ]:
#Save cleaned datasheet

df.to_csv("cleaned_cars_data.csv", index = False)
print("\nCleaned CSV file saved as cleaned_cars_data")

Cleaned CSV file saved as cleaned_cars_data