#Experiment 10 - Create and load dataset
###kushal warade
###ENTC A2
###25070123174

In [ ]:
#Dataset creation

import pandas as pd

data = {
    "Roll no": [176,175,174,173,172,171,170],
    "Gender": ["Female","Female","Male","Male","Female","Male","Female"],
    "Department": ["MECHANICAL","ENTC","METALLURGY","CSE","AIML","CIVIL","ROBOTICS"],
    "CGPA": [8.99, 9.54, 6.87, 5.87, 7.86, 8.54, 7.77],
}

df = pd.DataFrame(data)

df.to_csv("dataset.csv", index=False) #converting file to csv (index is false to not include "index" column in csv file)

df

   Roll no  Gender  Department  CGPA  Batch
0      176  Female  MECHANICAL  8.99   2024
1      175  Female        ENTC  9.54   2025
2      174    Male  METALLURGY  6.87   2023
3      173    Male         CSE  5.87   2022
4      172  Female        AIML  7.86   2021
5      171    Male       CIVIL  8.54   2025
6      170  Female    ROBOTICS  7.77   2024

In [ ]:
df["Batch"] = [2024, 2025, 2023, 2022, 2021, 2025, 2024]
df

   Roll no  Gender  Department  CGPA  Batch
0      176  Female  MECHANICAL  8.99   2024
1      175  Female        ENTC  9.54   2025
2      174    Male  METALLURGY  6.87   2023
3      173    Male         CSE  5.87   2022
4      172  Female        AIML  7.86   2021
5      171    Male       CIVIL  8.54   2025
6      170  Female    ROBOTICS  7.77   2024

In [ ]:
df.shape

(7, 5)

In [ ]:
df.size

35

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll no     7 non-null      int64
 1   Gender      7 non-null      object
 2   Department  7 non-null      object
 3   CGPA        7 non-null      float64
 4   Batch       7 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 412.0+ bytes

In [ ]:
df.describe()

          Roll no      CGPA        Batch
count    7.000000  7.000000     7.000000
mean   173.000000  7.920000  2023.428571
std      2.160247  1.257299     1.511858
min    170.000000  5.870000  2021.000000
25%    171.500000  7.320000  2022.500000
50%    173.000000  7.860000  2024.000000
75%    174.500000  8.765000  2024.500000
max    176.000000  9.540000  2025.000000

In [ ]:
#Problem statement 1 - Access informantion of department column

df["Department"]

0    MECHANICAL
1          ENTC
2    METALLURGY
3           CSE
4          AIML
5         CIVIL
6      ROBOTICS
Name: Department, dtype: object

In [ ]:
#Problem 2 - Access information of prn 175

df.loc[1]

Roll no          175
Gender        Female
Department      ENTC
CGPA            9.54
Batch           2025
Name: 1, dtype: object

In [ ]:
#Problem 3 - Find data type of each column

df.dtypes

Roll no         int64
Gender         object
Department     object
CGPA          float64
Batch           int64
dtype: object

In [ ]:
#Problem 4 - Perform mean, mediam, mode

mean = df["CGPA"].mean()
print("Mean:", mean)

median = df["CGPA"].median()
print("Median:", median)

mode = df["CGPA"].mode()
print("Mode:", mode)

Mean: 7.92
Median: 7.86
Mode: 0    5.87
1    6.87
2    7.77
3    7.86
4    8.54
5    8.99
6    9.54
Name: CGPA, dtype: float64

In [ ]:
#Problem 5 - Insert a new column grade

df["Grade"] = ["A","O","C","D","B","B","B"]
df

   Roll no  Gender  Department  CGPA  Batch Grade
0      176  Female  MECHANICAL  8.99   2024     A
1      175  Female        ENTC  9.54   2025     O
2      174    Male  METALLURGY  6.87   2023     C
3      173    Male         CSE  5.87   2022     D
4      172  Female        AIML  7.86   2021     B
5      171    Male       CIVIL  8.54   2025     B
6      170  Female    ROBOTICS  7.77   2024     B

In [ ]:
#Problem 6 - Delete gender

del df["Gender"]
df

   Roll no  Department  CGPA  Batch Grade
0      176  MECHANICAL  8.99   2024     A
1      175        ENTC  9.54   2025     O
2      174  METALLURGY  6.87   2023     C
3      173         CSE  5.87   2022     D
4      172        AIML  7.86   2021     B
5      171       CIVIL  8.54   2025     B
6      170    ROBOTICS  7.77   2024     B

In [ ]:
#Problem 7 - CGPA of topper

df["CGPA"].max()

9.54

In [ ]:
#Problem 8 - CGPA of PRN 171

df[df["Roll no"]==171]["CGPA"]

5    8.54
Name: CGPA, dtype: float64

###Dataset 2 - Cars93

In [ ]:
#Upload dataset from system

import pandas as pd
import numpy as np

df = pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.size

930

In [ ]:
df.shape

(93, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000