#Experiment 13 - Data binning and Data formatting using python
###Kushal warade
###25070123174
###ENTC - A2

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Product' : ['Laptop', 'Camera', 'Mobiles', 'Smartwatch', 'Tablet', 'Headphones'],
    'Price' : [125000, 50000, 80000, 40000, 30000, 10000 ],
    'Units_sold' : [100, 50, 200, 60, 40, 75]
    }

df = pd.DataFrame(data)
print(df)

      Product   Price  Units_sold
0      Laptop  125000         100
1      Camera   50000          50
2     Mobiles   80000         200
3  Smartwatch   40000          60
4      Tablet   30000          40
5  Headphones   10000          75

In [ ]:
#Data binning

bins1 =  [0, 50000, 100000, 150000]
labels1 = ['Low', 'Medium', 'High']

df['Price_Category'] = pd.cut(df['Price'], bins=bins1, labels=labels1)
print(df)

      Product   Price  Units_sold Price_Category
0      Laptop  125000         100           High
1      Camera   50000          50            Low
2     Mobiles   80000         200         Medium
3  Smartwatch   40000          60            Low
4      Tablet   30000          40            Low
5  Headphones   10000          75            Low

In [ ]:
#Binning units sold

bins2 = [0, 50, 100, 200]
labels2 = ['Low sold', 'Moderate sold', 'High sold']

df['Units_Category'] = pd.cut(df['Units_sold'], bins=bins2, labels=labels2)
print(df)

      Product   Price  Units_sold Price_Category Units_Category
0      Laptop  125000         100           High  Moderate sold
1      Camera   50000          50            Low       Low sold
2     Mobiles   80000         200         Medium      High sold
3  Smartwatch   40000          60            Low  Moderate sold
4      Tablet   30000          40            Low       Low sold
5  Headphones   10000          75            Low  Moderate sold

###Data Formatting

In [ ]:
#Convert data types

print(df.dtypes)

df['Price'] = df['Price'].astype(float)

print(df.dtypes)

Product             object
Price                int64
Units_sold           int64
Price_Category    category
Units_Category    category
dtype: object
Product             object
Price              float64
Units_sold           int64
Price_Category    category
Units_Category    category
dtype: object

In [ ]:
df

      Product     Price  Units_sold Price_Category Units_Category
0      Laptop  125000.0         100           High  Moderate sold
1      Camera   50000.0          50            Low       Low sold
2     Mobiles   80000.0         200         Medium      High sold
3  Smartwatch   40000.0          60            Low  Moderate sold
4      Tablet   30000.0          40            Low       Low sold
5  Headphones   10000.0          75            Low  Moderate sold

In [ ]:
#Convert Text to uppercase

df['Product'] = df['Product'].str.upper()
print(df)

      Product     Price  Units_sold Price_Category Units_Category
0      LAPTOP  125000.0         100           High  Moderate sold
1      CAMERA   50000.0          50            Low       Low sold
2     MOBILES   80000.0         200         Medium      High sold
3  SMARTWATCH   40000.0          60            Low  Moderate sold
4      TABLET   30000.0          40            Low       Low sold
5  HEADPHONES   10000.0          75            Low  Moderate sold

In [ ]:
#Rounding values

df['Price'] = df['Price'].round(2)
print(df)

      Product     Price  Units_sold Price_Category Units_Category
0      LAPTOP  125000.0         100           High  Moderate sold
1      CAMERA   50000.0          50            Low       Low sold
2     MOBILES   80000.0         200         Medium      High sold
3  SMARTWATCH   40000.0          60            Low  Moderate sold
4      TABLET   30000.0          40            Low       Low sold
5  HEADPHONES   10000.0          75            Low  Moderate sold

###Additional operators

In [ ]:
#Sort data

sorted_df = df.sort_values(by='Price')
print(sorted_df)

      Product     Price  Units_sold Price_Category Units_Category
5  HEADPHONES   10000.0          75            Low  Moderate sold
4      TABLET   30000.0          40            Low       Low sold
3  SMARTWATCH   40000.0          60            Low  Moderate sold
1      CAMERA   50000.0          50            Low       Low sold
2     MOBILES   80000.0         200         Medium      High sold
0      LAPTOP  125000.0         100           High  Moderate sold

In [ ]:
#Display unique values

print(df['Price_Category'].unique())

['High', 'Low', 'Medium']
Categories (3, object): ['Low' < 'Medium' < 'High']

###Dataset 2 - Food delivery orders

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Order_ID' : [101, 102, 103, 104, 105, 106, 107 , 108],
    '0rder_Value' : [250, 300, 550, 400, 380, 700, 675, 900],
    'Delivery_time' : [30, 15, 37, 45, 55, 20, 22, 48],
    'Distance_KM' : [5,2,6,7,4,8,3,9]
}
df = pd.DataFrame(data)
print(df)

   Order_ID  0rder_Value  Delivery_time  Distance_KM
0       101          250             30            5
1       102          300             15            2
2       103          550             37            6
3       104          400             45            7
4       105          380             55            4
5       106          700             20            8
6       107          675             22            3
7       108          900             48            9

In [ ]:
#Binning order value

bins = [0, 300, 500, 1000]
labels = ['Low value', 'Medium value', 'High value']

df['Order_Value_Category'] = pd.cut(df['0rder_Value'], bins=bins, labels=labels)
print(df)

   Order_ID  0rder_Value  Delivery_time  Distance_KM Order_Value_Category
0       101          250             30            5            Low value
1       102          300             15            2            Low value
2       103          550             37            6           High value
3       104          400             45            7         Medium value
4       105          380             55            4         Medium value
5       106          700             20            8           High value
6       107          675             22            3           High value
7       108          900             48            9           High value

In [ ]:
#Binning delivery time

bins1 = [0,25,40,60]
labels1 = ['Fast', 'Average', 'Slow']

df['Delivery_speed'] = pd.cut(df['Delivery_time'], bins=bins1, labels=labels1)
print(df)

   Order_ID  0rder_Value  Delivery_time  Distance_KM Order_Value_Category  \
0       101          250             30            5            Low value
1       102          300             15            2            Low value
2       103          550             37            6           High value
3       104          400             45            7         Medium value
4       105          380             55            4         Medium value
5       106          700             20            8           High value
6       107          675             22            3           High value
7       108          900             48            9           High value

  Delivery_speed
0        Average
1           Fast
2        Average
3           Slow
4           Slow
5           Fast
6           Fast
7           Slow

In [ ]:
#Data formatting - converting distance to float

df['Distance_KM'] = df['Distance_KM'].astype(float)
df

,Order_ID,0rder_Value,Delivery_time,Distance_KM,Order_Value_Category,Delivery_speed
0,101,250,30,5.0,Low value,Average
1,102,300,15,2.0,Low value,Fast
2,103,550,37,6.0,High value,Average
3,104,400,45,7.0,Medium value,Slow
4,105,380,55,4.0,Medium value,Slow
5,106,700,20,8.0,High value,Fast
6,107,675,22,3.0,High value,Fast
7,108,900,48,9.0,High value,Slow

In [ ]:
#Convert Order category to uppercase

df['Order_Value_Category'] = df['Order_Value_Category'].str.upper()
df

,Order_ID,0rder_Value,Delivery_time,Distance_KM,Order_Value_Category,Delivery_speed
0,101,250,30,5.0,LOW VALUE,Average
1,102,300,15,2.0,LOW VALUE,Fast
2,103,550,37,6.0,HIGH VALUE,Average
3,104,400,45,7.0,MEDIUM VALUE,Slow
4,105,380,55,4.0,MEDIUM VALUE,Slow
5,106,700,20,8.0,HIGH VALUE,Fast
6,107,675,22,3.0,HIGH VALUE,Fast
7,108,900,48,9.0,HIGH VALUE,Slow

In [ ]:
#Checking data types

print(df.dtypes)

Order_ID                   int64
0rder_Value                int64
Delivery_time              int64
Distance_KM              float64
Order_Value_Category      object
Delivery_speed          category
dtype: object

In [ ]:
#Unique categories

print(df['Order_Value_Category'].unique())
df

['LOW VALUE' 'HIGH VALUE' 'MEDIUM VALUE']

,Order_ID,0rder_Value,Delivery_time,Distance_KM,Order_Value_Category,Delivery_speed
0,101,250,30,5.0,LOW VALUE,Average
1,102,300,15,2.0,LOW VALUE,Fast
2,103,550,37,6.0,HIGH VALUE,Average
3,104,400,45,7.0,MEDIUM VALUE,Slow
4,105,380,55,4.0,MEDIUM VALUE,Slow
5,106,700,20,8.0,HIGH VALUE,Fast
6,107,675,22,3.0,HIGH VALUE,Fast
7,108,900,48,9.0,HIGH VALUE,Slow

In [ ]:
#Count of categories

print(df['Order_Value_Category'].value_counts())
df

Order_Value_Category
HIGH VALUE      4
LOW VALUE       2
MEDIUM VALUE    2
Name: count, dtype: int64

,Order_ID,0rder_Value,Delivery_time,Distance_KM,Order_Value_Category,Delivery_speed
0,101,250,30,5.0,LOW VALUE,Average
1,102,300,15,2.0,LOW VALUE,Fast
2,103,550,37,6.0,HIGH VALUE,Average
3,104,400,45,7.0,MEDIUM VALUE,Slow
4,105,380,55,4.0,MEDIUM VALUE,Slow
5,106,700,20,8.0,HIGH VALUE,Fast
6,107,675,22,3.0,HIGH VALUE,Fast
7,108,900,48,9.0,HIGH VALUE,Slow

In [ ]:
#Sorting

print(df.sort_values(by='Order_Value_Category'))
df

   Order_ID  0rder_Value  Delivery_time  Distance_KM Order_Value_Category  \
2       103          550             37          6.0           HIGH VALUE
5       106          700             20          8.0           HIGH VALUE
6       107          675             22          3.0           HIGH VALUE
7       108          900             48          9.0           HIGH VALUE
0       101          250             30          5.0            LOW VALUE
1       102          300             15          2.0            LOW VALUE
3       104          400             45          7.0         MEDIUM VALUE
4       105          380             55          4.0         MEDIUM VALUE

  Delivery_speed
2        Average
5           Fast
6           Fast
7           Slow
0        Average
1           Fast
3           Slow
4           Slow

,Order_ID,0rder_Value,Delivery_time,Distance_KM,Order_Value_Category,Delivery_speed
0,101,250,30,5.0,LOW VALUE,Average
1,102,300,15,2.0,LOW VALUE,Fast
2,103,550,37,6.0,HIGH VALUE,Average
3,104,400,45,7.0,MEDIUM VALUE,Slow
4,105,380,55,4.0,MEDIUM VALUE,Slow
5,106,700,20,8.0,HIGH VALUE,Fast
6,107,675,22,3.0,HIGH VALUE,Fast
7,108,900,48,9.0,HIGH VALUE,Slow