###  Data normalization and Data type conversion
###kushal warade
###25070123174
###ENTC A2

## 14A -Data Normalization

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Product' : ['Laptop', 'Camera', 'Mobiles', 'Smartwatch', 'Tablet', 'Headphones'],
    'Price' : [125000, 50000, 80000, 40000, 30000, 10000 ],
    'Units_sold' : [100, 50, 200, 60, 40, 75],
    'Discount' : [10, 8, 18, 12, 20, 15]
    }

df = pd.DataFrame(data)
print("Original datasheet")
print(df)

Original datasheet
      Product   Price  Units_sold  Discount
0      Laptop  125000         100        10
1      Camera   50000          50         8
2     Mobiles   80000         200        18
3  Smartwatch   40000          60        12
4      Tablet   30000          40        20
5  Headphones   10000          75        15

###Min-Max normalization

In [ ]:
#Min-Max normalization for price :

df['Price_MinMax'] = (df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())

print("\nMix-Max Normalized Price")
print(df[['Product','Price','Price_MinMax']])

Mix-Max Normalized Price
      Product   Price  Price_MinMax
0      Laptop  125000      1.000000
1      Camera   50000      0.347826
2     Mobiles   80000      0.608696
3  Smartwatch   40000      0.260870
4      Tablet   30000      0.173913
5  Headphones   10000      0.000000

In [ ]:
#Min-Max normalization for discounts :

df['Discount_MinMax'] = (df['Discount']-df['Discount'].min())/(df['Discount'].max()-df['Discount'].min())

print("\nMix-Max Normalized Discount")
print(df[['Product','Discount','Discount_MinMax']])

Mix-Max Normalized Discount
      Product  Discount  Discount_MinMax
0      Laptop        10         0.166667
1      Camera         8         0.000000
2     Mobiles        18         0.833333
3  Smartwatch        12         0.333333
4      Tablet        20         1.000000
5  Headphones        15         0.583333

In [ ]:
#Min-Max normalization for units sold :

df['Units_sold_MinMax'] = (df['Units_sold']-df['Units_sold'].min())/(df['Units_sold'].max()-df['Units_sold'].min())

print("\nMix-Max Normalized Units_sold")
print(df[['Product','Units_sold','Units_sold_MinMax']])

Mix-Max Normalized Units_sold
      Product  Units_sold  Units_sold_MinMax
0      Laptop         100            0.37500
1      Camera          50            0.06250
2     Mobiles         200            1.00000
3  Smartwatch          60            0.12500
4      Tablet          40            0.00000
5  Headphones          75            0.21875

In [ ]:
#Z-score normalization :

df['Units_Zscore'] = (df['Units_sold'] - df['Units_sold'].mean())/df['Units_sold'].std()

print("\nZ-score Normalized Units_sold")
print(df[['Product', 'Units_sold', 'Units_Zscore']])

Z-score Normalized Units_sold
      Product  Units_sold  Units_Zscore
0      Laptop         100      0.211971
1      Camera          50     -0.635913
2     Mobiles         200      1.907739
3  Smartwatch          60     -0.466336
4      Tablet          40     -0.805490
5  Headphones          75     -0.211971

###Decimal scaling

In [ ]:
#Decimal scaling for price :

df['Price_Decimal'] = df['Price']/1000000

print("\nDecimal Scaled Price")
print(df[['Product', 'Price', 'Price_Decimal']])

Decimal Scaled Price
      Product   Price  Price_Decimal
0      Laptop  125000          0.125
1      Camera   50000          0.050
2     Mobiles   80000          0.080
3  Smartwatch   40000          0.040
4      Tablet   30000          0.030
5  Headphones   10000          0.010

In [ ]:
#Decimal scaling for discount :

df['Discount_Decimal'] = df['Discount']/100

print("\nDecimal Scaled Discount")
print(df[['Product', 'Discount', 'Discount_Decimal']])

Decimal Scaled Discount
      Product  Discount  Discount_Decimal
0      Laptop        10              0.10
1      Camera         8              0.08
2     Mobiles        18              0.18
3  Smartwatch        12              0.12
4      Tablet        20              0.20
5  Headphones        15              0.15

In [ ]:
#Normalize multiple columns

cols = ['Price', 'Units_sold', 'Discount']
df_norm = (df[cols]-df[cols].min()) / (df[cols].max()-df[cols].min())

print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
      Price  Units_sold  Discount
0  1.000000     0.37500  0.166667
1  0.347826     0.06250  0.000000
2  0.608696     1.00000  0.833333
3  0.260870     0.12500  0.333333
4  0.173913     0.00000  1.000000
5  0.000000     0.21875  0.583333

##14B - Turning categorical variables into quantitive variables in python

In [ ]:
data = {

'OrderID' : [ '01', '02', '03', '04', '05', '06', '07', '08', '09', '10'],

'Category' : [ 'Electronics', 'Clothing', 'Cosmetics', 'Grocery', 'Clothing', 'Electronics', 'Cosmetics', 'Grocery', 'Grocery', 'Clothing'],

'Payment' : ['UPI', 'COD', 'UPI', 'Netbanking', 'UPI', "COD", "UPI", "UPI", "Netbanking", "UPI"],

'Customer_gender' : ['Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Male'],

'City' : ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Delhi', 'Pune', 'Lucknow', 'Pune', 'Delhi', 'Lucknow'],

'Order_value' :[4500, 5000, 900, 1800, 3300, 7860, 2300, 4855, 3500, 6000]
}

df = pd.DataFrame(data)

print(df)

  OrderID     Category     Payment Customer_gender       City  Order_value
0      01  Electronics         UPI          Female     Mumbai         4500
1      02     Clothing         COD          Female      Delhi         5000
2      03    Cosmetics         UPI            Male  Bangalore          900
3      04      Grocery  Netbanking          Female    Chennai         1800
4      05     Clothing         UPI            Male      Delhi         3300
5      06  Electronics         COD          Female       Pune         7860
6      07    Cosmetics         UPI            Male    Lucknow         2300
7      08      Grocery         UPI          Female       Pune         4855
8      09      Grocery  Netbanking            Male      Delhi         3500
9      10     Clothing         UPI            Male    Lucknow         6000

In [ ]:
#Method 1 - Label encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender_Label'] = le.fit_transform(df['Customer_gender'])

print(df)

  OrderID     Category     Payment Customer_gender       City  Order_value  \
0      01  Electronics         UPI          Female     Mumbai         4500
1      02     Clothing         COD          Female      Delhi         5000
2      03    Cosmetics         UPI            Male  Bangalore          900
3      04      Grocery  Netbanking          Female    Chennai         1800
4      05     Clothing         UPI            Male      Delhi         3300
5      06  Electronics         COD          Female       Pune         7860
6      07    Cosmetics         UPI            Male    Lucknow         2300
7      08      Grocery         UPI          Female       Pune         4855
8      09      Grocery  Netbanking            Male      Delhi         3500
9      10     Clothing         UPI            Male    Lucknow         6000

   Gender_Label
0             0
1             0
2             1
3             0
4             1
5             0
6             1
7             0
8             1
9             1

In [ ]:
#Method 2: One-Hot encoding:

df_encoded = pd.get_dummies(df, columns=['Payment'])

print(df_encoded)

  OrderID     Category Customer_gender       City  Order_value  Gender_Label  \
0      01  Electronics          Female     Mumbai         4500             0
1      02     Clothing          Female      Delhi         5000             0
2      03    Cosmetics            Male  Bangalore          900             1
3      04      Grocery          Female    Chennai         1800             0
4      05     Clothing            Male      Delhi         3300             1
5      06  Electronics          Female       Pune         7860             0
6      07    Cosmetics            Male    Lucknow         2300             1
7      08      Grocery          Female       Pune         4855             0
8      09      Grocery            Male      Delhi         3500             1
9      10     Clothing            Male    Lucknow         6000             1

   Payment_COD  Payment_Netbanking  Payment_UPI
0        False               False         True
1         True               False        False
2        False               False         True
3        False                True        False
4        False               False         True
5         True               False        False
6        False               False         True
7        False               False         True
8        False                True        False
9        False               False         True

In [ ]:
#Method 3 : Encoding multiple columns

df_mult = pd.get_dummies(df, columns=['Category', 'City'])

print(df_mult)

  OrderID     Payment Customer_gender  Order_value  Gender_Label  \
0      01         UPI          Female         4500             0
1      02         COD          Female         5000             0
2      03         UPI            Male          900             1
3      04  Netbanking          Female         1800             0
4      05         UPI            Male         3300             1
5      06         COD          Female         7860             0
6      07         UPI            Male         2300             1
7      08         UPI          Female         4855             0
8      09  Netbanking            Male         3500             1
9      10         UPI            Male         6000             1

   Category_Clothing  Category_Cosmetics  Category_Electronics  \
0              False               False                  True
1               True               False                 False
2              False                True                 False
3              False               False                 False
4               True               False                 False
5              False               False                  True
6              False                True                 False
7              False               False                 False
8              False               False                 False
9               True               False                 False

   Category_Grocery  City_Bangalore  City_Chennai  City_Delhi  City_Lucknow  \
0             False           False         False       False         False
1             False           False         False        True         False
2             False            True         False       False         False
3              True           False          True       False         False
4             False           False         False        True         False
5             False           False         False       False         False
6             False           False         False       False          True
7              True           False         False       False         False
8              True           False         False        True         False
9             False           False         False       False          True

   City_Mumbai  City_Pune
0         True      False
1        False      False
2        False      False
3        False      False
4        False      False
5        False       True
6        False      False
7        False       True
8        False      False
9        False      False

In [ ]:
#Method 4 : Dummy encoding (Drop first)

df_dummy = pd.get_dummies(df, columns=['Payment'], drop_first=True)

print(df_dummy)

  OrderID     Category Customer_gender       City  Order_value  Gender_Label  \
0      01  Electronics          Female     Mumbai         4500             0
1      02     Clothing          Female      Delhi         5000             0
2      03    Cosmetics            Male  Bangalore          900             1
3      04      Grocery          Female    Chennai         1800             0
4      05     Clothing            Male      Delhi         3300             1
5      06  Electronics          Female       Pune         7860             0
6      07    Cosmetics            Male    Lucknow         2300             1
7      08      Grocery          Female       Pune         4855             0
8      09      Grocery            Male      Delhi         3500             1
9      10     Clothing            Male    Lucknow         6000             1

   Payment_Netbanking  Payment_UPI
0               False         True
1               False        False
2               False         True
3                True        False
4               False         True
5               False        False
6               False         True
7               False         True
8                True        False
9               False         True

##Amazon products dataset

In [ ]:
#uploadig dataset
import pandas as pd

df = pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

###Data Normalixation

In [ ]:
#Normalize multiple columns with Min-Max:

cols = ['Price', 'Rating', 'Reviews','Units_Sold']
df_norm = (df[cols]-df[cols].min()) / (df[cols].max()-df[cols].min())

print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
       Price    Rating   Reviews  Units_Sold
0   0.020243  0.428571  0.291005    0.518519
1   0.048583  0.714286  0.148148    0.277778
2   0.016194  0.142857  0.119048    0.203704
3   0.089069  0.857143  0.444444    0.629630
4   0.149798  0.571429  0.695767    0.833333
5   0.036437  0.285714  0.351852    0.592593
6   0.024291  0.000000  0.052910    0.129630
7   0.064777  0.428571  0.185185    0.351852
8   0.210526  1.000000  0.378307    0.481481
9   0.028340  0.285714  0.089947    0.222222
10  0.311741  0.857143  1.000000    1.000000
11  0.174089  0.714286  0.444444    0.407407
12  0.052632  0.571429  0.232804    0.500000
13  0.016194  0.142857  0.031746    0.092593
14  0.024291  0.285714  0.119048    0.240741
15  0.251012  0.857143  0.497354    0.444444
16  0.036437  0.428571  0.089947    0.259259
17  0.068826  0.571429  0.312169    0.648148
18  0.109312  0.714286  0.814815    0.851852
19  0.040486  0.428571  0.148148    0.351852
20  0.008097  0.000000  0.000000    0.148148
21  0.089069  0.571429  0.272487    0.444444
22  0.352227  0.857143  0.219577    0.185185
23  0.020243  0.285714  0.079365    0.259259
24  0.129555  0.714286  0.444444    0.592593
25  0.174089  0.571429  0.148148    0.166667
26  0.514170  1.000000  0.708995    0.129630
27  0.076923  0.428571  0.232804    0.370370
28  0.016194  0.285714  0.121693    0.314815
29  0.048583  0.428571  0.150794    0.351852
30  0.392713  0.857143  0.444444    0.240741
31  0.230769  0.714286  0.351852    0.203704
32  0.129555  0.571429  0.550265    0.666667
33  0.473684  0.857143  0.272487    0.092593
34  0.635628  1.000000  0.444444    0.037037
35  0.012146  0.142857  0.007937    0.166667
36  0.020243  0.285714  0.126984    0.462963
37  0.000000  0.000000  0.047619    0.574074
38  0.028340  0.428571  0.079365    0.259259
39  0.048583  0.571429  0.026455    0.111111
40  0.109312  0.714286  0.113757    0.148148
41  0.433198  0.857143  0.206349    0.074074
42  0.190283  0.571429  0.444444    0.351852
43  1.000000  1.000000  0.365079    0.000000
44  0.068826  0.428571  0.259259    0.444444
45  0.311741  0.857143  0.470899    0.240741
46  0.757085  0.714286  0.325397    0.092593
47  0.089069  0.571429  0.148148    0.185185
48  0.129555  0.428571  0.119048    0.148148
49  0.028340  0.285714  0.089947    0.314815

In [ ]:
#Normalize data with Z score:

df_Zscore = (df[cols]-df[cols].mean())/df[cols].std()

print("\nZ-score Normalized Dataset")
print(df_Zscore)

Z-score Normalized Dataset
       Price    Rating   Reviews  Units_Sold
0  -0.692019 -0.421580  0.075943    0.812282
1  -0.557310  0.606665 -0.577069   -0.260855
2  -0.711263 -1.449825 -0.710090   -0.591051
3  -0.364869  1.120787  0.777327    1.307576
4  -0.076207  0.092542  1.926145    2.215615
5  -0.615043 -0.935703  0.354078    1.142478
6  -0.672775 -1.963948 -1.012411   -0.921247
7  -0.480334 -0.421580 -0.407770    0.069341
8   0.212455  1.634910  0.475006    0.647184
9  -0.653531 -0.935703 -0.843111   -0.508502
10  0.693559  1.120787  3.316819    2.958556
11  0.039258  0.606665  0.777327    0.316988
12 -0.538066  0.092542 -0.190099    0.729733
13 -0.711263 -1.449825 -1.109154   -1.086345
14 -0.672775 -0.935703 -0.710090   -0.425953
15  0.404897  1.120787  1.019183    0.482086
16 -0.615043 -0.421580 -0.843111   -0.343404
17 -0.461090  0.092542  0.172685    1.390125
18 -0.268648  0.606665  2.470321    2.298164
19 -0.595799 -0.421580 -0.577069    0.069341
20 -0.749752 -1.963948 -1.254267   -0.838698
21 -0.364869  0.092542 -0.008707    0.482086
22  0.886000  1.120787 -0.250563   -0.673600
23 -0.692019 -0.935703 -0.891483   -0.343404
24 -0.172428  0.606665  0.777327    1.142478
25  0.039258  0.092542 -0.577069   -0.756149
26  1.655766  1.634910  1.986609   -0.921247
27 -0.422601 -0.421580 -0.190099    0.151890
28 -0.711263 -0.935703 -0.697998   -0.095757
29 -0.557310 -0.421580 -0.564977    0.069341
30  1.078442  1.120787  0.777327   -0.425953
31  0.308676  0.606665  0.354078   -0.591051
32 -0.172428  0.092542  1.261039    1.472674
33  1.463325  1.120787 -0.008707   -1.086345
34  2.233090  1.634910  0.777327   -1.333992
35 -0.730508 -1.449825 -1.217989   -0.756149
36 -0.692019 -0.935703 -0.673812    0.564635
37 -0.788240 -1.963948 -1.036597    1.059929
38 -0.653531 -0.421580 -0.891483   -0.343404
39 -0.557310  0.092542 -1.133339   -1.003796
40 -0.268648  0.606665 -0.734276   -0.838698
41  1.270883  1.120787 -0.311027   -1.168894
42  0.116235  0.092542  0.777327    0.069341
43  3.965063  1.634910  0.414542   -1.499090
44 -0.461090 -0.421580 -0.069171    0.482086
45  0.693559  1.120787  0.898255   -0.425953
46  2.810415  0.606665  0.233150   -1.086345
47 -0.364869  0.092542 -0.577069   -0.673600
48 -0.172428 -0.421580 -0.710090   -0.838698
49 -0.653531 -0.935703 -0.843111   -0.095757

In [ ]:
#Normalize data with decimal scaling for rating:

df['Rating_decimal'] = df['Rating']/10

print("\nDecimal Scaled Dataset")
print(df[['Product_Name','Rating_decimal']])

Decimal Scaled Dataset
                   Product_Name  Rating_decimal
0                Wireless Mouse            0.43
1             Bluetooth Speaker            0.45
2                  USB Keyboard            0.41
3                Gaming Headset            0.46
4                    Smartwatch            0.44
5                    Power Bank            0.42
6                  Laptop Stand            0.40
7                        Webcam            0.43
8                  Portable SSD            0.47
9              Wireless Charger            0.42
10  Noise Cancelling Headphones            0.46
11          Mechanical Keyboard            0.45
12                 Gaming Mouse            0.44
13                 Tablet Stand            0.41
14                      USB Hub            0.42
15          External Hard Drive            0.46
16            Smartphone Tripod            0.43
17              Laptop Backpack            0.44
18            Bluetooth Earbuds            0.45
19                LED Desk Lamp            0.43
20                 Phone Holder            0.40
21            Wireless Keyboard            0.44
22             Portable Monitor            0.46
23                   Smart Plug            0.42
24                  WiFi Router            0.45
25              Graphics Tablet            0.44
26                   VR Headset            0.47
27                   Microphone            0.43
28             Smart Light Bulb            0.42
29           Laptop Cooling Pad            0.43
30                Action Camera            0.46
31               Smart Doorbell            0.45
32              Streaming Stick            0.44
33           Portable Projector            0.46
34                 Gaming Chair            0.47
35               Desk Organizer            0.41
36              USB Flash Drive            0.42
37       Phone Screen Protector            0.40
38                Laptop Sleeve            0.43
39           Wireless Presenter            0.44
40         Tablet Keyboard Case            0.45
41             Smart Thermostat            0.46
42              Security Camera            0.44
43                 Drone Camera            0.47
44              Electric Kettle            0.43
45                    Air Fryer            0.46
46                 Robot Vacuum            0.45
47                  Smart Scale            0.44
48          Digital Photo Frame            0.43
49                 Portable Fan            0.42

In [ ]:
#Normalize data with decimal scaling for rating:

df['Units_Sold_decimal'] = df['Units_Sold']/1000

print("\nDecimal Scaled Dataset")
print(df[['Product_Name','Units_Sold_decimal']])

Decimal Scaled Dataset
                   Product_Name  Units_Sold_decimal
0                Wireless Mouse                0.35
1             Bluetooth Speaker                0.22
2                  USB Keyboard                0.18
3                Gaming Headset                0.41
4                    Smartwatch                0.52
5                    Power Bank                0.39
6                  Laptop Stand                0.14
7                        Webcam                0.26
8                  Portable SSD                0.33
9              Wireless Charger                0.19
10  Noise Cancelling Headphones                0.61
11          Mechanical Keyboard                0.29
12                 Gaming Mouse                0.34
13                 Tablet Stand                0.12
14                      USB Hub                0.20
15          External Hard Drive                0.31
16            Smartphone Tripod                0.21
17              Laptop Backpack                0.42
18            Bluetooth Earbuds                0.53
19                LED Desk Lamp                0.26
20                 Phone Holder                0.15
21            Wireless Keyboard                0.31
22             Portable Monitor                0.17
23                   Smart Plug                0.21
24                  WiFi Router                0.39
25              Graphics Tablet                0.16
26                   VR Headset                0.14
27                   Microphone                0.27
28             Smart Light Bulb                0.24
29           Laptop Cooling Pad                0.26
30                Action Camera                0.20
31               Smart Doorbell                0.18
32              Streaming Stick                0.43
33           Portable Projector                0.12
34                 Gaming Chair                0.09
35               Desk Organizer                0.16
36              USB Flash Drive                0.32
37       Phone Screen Protector                0.38
38                Laptop Sleeve                0.21
39           Wireless Presenter                0.13
40         Tablet Keyboard Case                0.15
41             Smart Thermostat                0.11
42              Security Camera                0.26
43                 Drone Camera                0.07
44              Electric Kettle                0.31
45                    Air Fryer                0.20
46                 Robot Vacuum                0.12
47                  Smart Scale                0.17
48          Digital Photo Frame                0.15
49                 Portable Fan                0.24

##Student sample dataset

In [ ]:
#Uploading dataset

import pandas as pd

df = pd.read_csv("/content/Student-Dataset.csv")
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
#Label encoding for placements:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Placement_Label'] = le.fit_transform(df['Placement_Status'])

print(df)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary  Placement_Label
0                     92           Placed  450000                1
1                     85       Not Placed       0                0
2                     96           Placed  550000                1
3                     78       Not Placed       0                0
4                     88           Placed  480000                1
5                     72       Not Placed       0                0
6                     91           Placed  500000                1
7                     80       Not Placed       0                0
8                     84           Placed  420000                1
9                     76       Not Placed       0                0

In [ ]:
#One hot encoding for department

df_encoded = pd.get_dummies(df, columns=['Department'])

print(df_encoded)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Label  Department_Civil  \
0           Placed  450000                1             False
1       Not Placed       0                0             False
2           Placed  550000                1             False
3       Not Placed       0                0             False
4           Placed  480000                1             False
5       Not Placed       0                0              True
6           Placed  500000                1             False
7       Not Placed       0                0             False
8           Placed  420000                1             False
9       Not Placed       0                0             False

   Department_Computer  Department_ENTC  Department_IT  Department_Mechanical
0                 True            False          False                  False
1                False            False           True                  False
2                False             True          False                  False
3                False            False          False                   True
4                 True            False          False                  False
5                False            False          False                  False
6                False            False           True                  False
7                 True            False          False                  False
8                False             True          False                  False
9                False            False          False                   True

In [ ]:
#Dummy encoding for department

df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)

print(df_dummy)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Label  Department_Computer  \
0           Placed  450000                1                 True
1       Not Placed       0                0                False
2           Placed  550000                1                False
3       Not Placed       0                0                False
4           Placed  480000                1                 True
5       Not Placed       0                0                False
6           Placed  500000                1                False
7       Not Placed       0                0                 True
8           Placed  420000                1                False
9       Not Placed       0                0                False

   Department_ENTC  Department_IT  Department_Mechanical
0            False          False                  False
1            False           True                  False
2             True          False                  False
3            False          False                   True
4            False          False                  False
5            False          False                  False
6            False           True                  False
7            False          False                  False
8             True          False                  False
9            False          False                   True